unbind C-b
set -g prefix F9

bind-key f popup -d "#{pane_current_path}"
bind-key h command-prompt -I "resize-pane -L "
bind-key j command-prompt -I "resize-pane -D "
bind-key k command-prompt -I "resize-pane -U "
bind-key l command-prompt -I "resize-pane -R "
# status
set -g status-interval 1
set -g status-left '┃#{?client_prefix,#[bg=blue] #[bold]PANDA-GO #[bg=default],          }┃ #[bold]#S #[fg=black]┃'
set -g status-left-length 30
set -g status-right '┃ #{pane_current_path} ┃ %Y-%m-%d %H:%M ┃'
set -g status-right-style 'bg=magenta'
set -g status-right-length 100

setw -g window-status-current-style "bg=brightmagenta"
setw -g window-status-current-format ' #I #W '

setw -g window-status-style "bg=magenta"
setw -g window-status-format ' #I #W '

setw -g window-status-separator '┃'

# continuum/resurrect
set -g @continuum-restore 'off'
set -g @continuum-save-interval '15'

# TPM + plugins
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'hamolicious/back-in-5'

set -g status-fg black
set -g status-style bg=magenta

set -g mouse on

run '~/.tmux/plugins/tpm/tpm'
